application: maumasi-liu-simple-form
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
  upload: https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js
  static_files: https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js

- url: /https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js
  upload: https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js
  static_files: https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js

- url: /https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css
  upload: https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css
  static_files: https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css

- url: /css/form.css
  upload: css/form.css
  static_files: css/form.css
  
- url: /imgs/borderlands_sniper-01.png
  upload: imgs/borderlands_sniper-01.png
  static_files: imgs/borderlands_sniper-01.png

- url: /js/app.js
  upload: js/app.js
  static_files: js/app.js

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
